name: Generate Snake and Metrics

# Controls when the action will run. The snake action runs every 6 hours.
on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  # Job for generating the snake animation
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        
      - name: Generate the snake files in './dist/'
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Show build status
        run: git status
        
      - name: Push github-snake.svg
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: snake
          build_dir: dist
          keep_history: no
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job for generating GitHub metrics
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Options
          user: ${{ github.repository_owner }}
          config_timezone: Europe/Paris
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
