# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake
# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
      # every 6 hours
    - cron: "0 */12 * * *"
# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
  push: {branches: ["master", "main"]}
# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v4
    # Generates the snake
      - name: Generate the snake files in './dist/'
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
              dist/github-snake.svg
              dist/github-snake-dark.svg?palette=github-dark
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status
        
      - name: push github-snake.svg
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: snake
          build_dir: dist
          keep_history: no
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
